VideoGame.DB.Base.URI=https://videogamedb.uk/api/v2/
Football.Data.Base.URI=https://api.football-data.org/v4
Test.Framework=REST Assured 5.3.0 + JUnit 4
Allure.Version=2.27.0
Java.Version=18
CI=GitHub Actions (ubuntu-latest)
